### PR TITLE
Integrates CircleCI for continuous integration and automated testing

### LINKED ISSUE #167: Use CircleCI for continuous integration
Derived from samvera/maintenance#16

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #167

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
Code Climate integration for this has to be evaluated, I am not confident that this is reporting properly.

**Comment by tpendragon** [comment]
@cjcolvar Can you look at this? You have more experience with CodeClimate than I do, and I know you had a draft set of related things in the Circle Orb.

**Comment by jrgriffiniii** [comment]
If it's preferred, I can look to push much of what was introduced in https://github.com/samvera/hydra-editor/pull/168/files#diff-1d37e48f9ceff6d8030570cd36286a61R82 upstream to https://github.com/samvera-labs/samvera-circleci-orb

**Comment by tpendragon** [comment]
I'm going to merge this and we can deal with it later.

**Pull request merged**
