### PR TITLE
Update CircleCI Ruby and Rails versions

### PR DESCRIPTION
**Pull request by botimer**
This gem had a particularly verbose config. This attempts to trim it
down and normalize with other gems that use engine_cart.

Re: samvera/maintenance#20
Re: samvera/maintenance#21

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
https://circleci.com/gh/samvera/hydra-editor/54?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link leads me to believe that `bundle install` has to be run either from inside of `.internal_test_app`, or outside of it after `engine_cart:generate` has finished.

**Comment by botimer** [comment]
Thanks, James. I mangled the clean-up in multiple ways... I've just restored the second `bundle_for_gem` (after engine_cart and before rubocop). Let's see if it's happy this time.

**Comment by botimer** [comment]
Hmmm... I'm not sure what's wrong, here. I modeled the simplification on hydra-derivatives. Maybe there is something weird with the caching, how I tried to use the orb, or fold the jobs together. Do you see anything obvious, @jrgriffiniii?

**Comment by jrgriffiniii** [comment]
I'm now trying with https://github.com/samvera/hydra-editor/compare/jul19-ruby-versions...jrgriffiniii:jul19-ruby-versions, I'll see if it passes on https://circleci.com/workflow-run/421c7d25-7b3a-405f-8437-fd24f9ebe4dd

**Comment by jrgriffiniii** [comment]
Looking at https://github.com/samvera/hydra-editor/pull/168/files, I don't think that Rubocop was a part of the Travis CI build.  I'm not certain what exactly is failing for the environment that leads to this.

**Comment by jrgriffiniii** [comment]
The latest commits to https://github.com/samvera/hydra-editor/compare/jul19-ruby-versions...jrgriffiniii:jul19-ruby-versions get it passing.  I'm going to experiment with another branch to try and get `rubocop` working.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-editor/pull/179 restores the build with Rubocop.  I think that the redundant `bundle install` invocations are necessary, but I can verify that this is the case tomorrow or Sunday.

**Pull request merged**
