### PR TITLE
Upgrading Ruby support for releases 3.0.3, 2.7.5, and 2.6.9

### LINKED ISSUE #200: Support Ruby 3.0.3
Derived from samvera/maintenance#77

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #200

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
Ruby 3.0.3 is failing with dependency errors, such as the following:

```
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    thor (~> 0.20)

    rails (= 5.2.3) was resolved to 5.2.3, which depends on
      railties (= 5.2.3) was resolved to 5.2.3, which depends on
        thor (< 2.0, >= 0.19.0)
```

**Comment by jrgriffiniii** [comment]
Even for Ruby 2.6, there are additional errors:

```
/usr/local/bundle/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Cannot load database configuration: (Psych::BadAlias)
Unknown alias: default
	from /usr/local/bundle/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
```

**Comment by jrgriffiniii** [comment]
Issue 42528 for https://github.com/rails/rails may be related to this.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-editor/pull/205/commits/fe720e7ae082696ed72e258244a7151c66a26874 did manage to resolve this for Ruby 2.6.9.

**Comment by jrgriffiniii** [comment]
Ruby 3.0.3 support may require an update for support from within `active_fedora`:

```bash
  hydra-editor was resolved to 6.0.0, which depends on
    active-fedora (>= 9.0.0) was resolved to 13.0.0, which depends on
      ruby (~> 2.0)
```

**Comment by jrgriffiniii** [comment]
This may well need to be deprecated entirely, as I am not able to consistently maintain a connection over the VPN.

**Comment by jrgriffiniii** [comment]
Returning to this, this also seems to be blocked by support within `hydra-head` for Ruby 3.0 releases.

**Comment by cjcolvar** [comment]
Replaced by #216

**Pull request closed without merging**
